### ISSUE TITLE
GenerateBenchmarkReport.py: TypeError: Could not convert to numeric

### ISSUE THREAD

**Issue by lixuemin2016** [SCHEN2015/virt-perf-scripts#4]
$ GenerateBenchmarkReport.py rhel74_fio_report.csv rhel75_830_fio_report.csv benchmark_report.csv
Reading base samples from csv file "rhel74_fio_report.csv"...
Reading test samples from csv file "rhel75_830_fio_report.csv"...
Traceback (most recent call last):
  File "/home/cheshi/bin/GenerateBenchmarkReport.py", line 364, in <module>
    generate_fio_benchmark_report()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cheshi/bin/GenerateBenchmarkReport.py", line 353, in generate_fio_benchmark_report
    fbr.generate_report()
  File "/home/cheshi/bin/GenerateBenchmarkReport.py", line 297, in generate_report
    self._complete_report_dataframe()
  File "/home/cheshi/bin/GenerateBenchmarkReport.py", line 264, in _complete_report_dataframe
    series, my_sub_base, my_sub_test, 'Util', 'Util(%)', True)
  File "/home/cheshi/bin/GenerateBenchmarkReport.py", line 210, in _calculate_and_fill_report_series
    series[label + '-TEST-AVG'] = df_test[source_label].mean()
  File "/usr/lib64/python2.7/site-packages/pandas/core/generic.py", line 7315, in stat_func
    numeric_only=numeric_only)
  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 2577, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/usr/lib64/python2.7/site-packages/pandas/core/nanops.py", line 77, in _f
    return f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/nanops.py", line 131, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/usr/lib64/python2.7/site-packages/pandas/core/nanops.py", line 356, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))
  File "/usr/lib64/python2.7/site-packages/pandas/core/nanops.py", line 825, in _ensure_numeric
    .format(value=x))
TypeError: Could not convert 99.91494299.93327999.91327899.93828299.911606 to numeric
$

**Comment by SCHEN2015** [comment]
This is because the "Util(%)" of some tuples are "error". As a solution, I will replace them with "NaN" which is more friendly to Pandas.

**Comment by SCHEN2015** [comment]
This bug was fixed.
